apiVersion: v1
kind: Service
metadata:
  name: weather-backend-svc
  labels:
    app: weather-backend
spec:
  type: NodePort
  selector:
    app: weather-backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
