apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-svc
  labels:
    app: weather-frontend
spec:
  type: NodePort
  selector:
    app: weather-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
    protocol: TCP
